# who gets notified if build-status changes
notifications: 
  email:
    recipients:
      - dr.sebastian.koehler@gmail.com
      - Peter.Robinson@jax.org
      - vasilevs@ohsu.edu
      - Leigh.Carmody@jax.org
      - haendel@ohsu.edu
    on_success: change
    on_failure: always

jdk:
  - oraclejdk8

# store the home dir for later use
env:
  global:
    - CI_HOME=`pwd`/$REPO
    - HP_EDIT=src/ontology/hp-edit.owl
    - HP_OBO=src/ontology/hp.obo
    - OBO_CHECK_JAR=hpo-obo-qc/target/hpo-obo-qc-0.0.1-SNAPSHOT-jar-with-dependencies.jar
    - OWL_CHECK_JAR=hpo-owl-qc/target/hpo-owl-qc-0.0.1-SNAPSHOT-jar-with-dependencies.jar

# get all jars
install:
  # owltools
  - cd $CI_HOME  
  - wget -i src/owltools/urls.txt
  # owl-qc
  - git clone https://github.com/Phenomics/hpo-owl-qc.git
  - cd hpo-owl-qc
  - mvn clean install
  # obo-qc
  - cd $CI_HOME
  - git clone https://github.com/Phenomics/hpo-obo-qc.git
  - cd hpo-obo-qc
  - mvn clean install
  # other steps, e.g. path-variable
  - cd $CI_HOME
  - mkdir -p owltools_folder
  - mv owltools owltools_folder/
  - mv *jar owltools_folder/
  - mv ontology-rel* owltools_folder/
  - chmod +x owltools_folder/*
  - export PATH="$PATH":`pwd`/owltools_folder/
  - export PATH="$PATH":`pwd`/hpo-owl-qc/target/
  - export PATH="$PATH":`pwd`/hpo-obo-qc/target/
  - export OORT_ARGS='--catalog-xml catalog-v001.xml' 

# perform quality checks
script:
  # run tests on hp-edit
   # encoding test
  - iconv -f UTF-8 -t ISO-8859-15 $HP_EDIT > converted.txt || (echo "found special characters in ontology. remove those!"; exit 1)
   # java-based owl checkss
  - java -jar $OWL_CHECK_JAR $HP_EDIT
  # build hp.owl and hp.obo
  - cd $CI_HOME  
  - cd src/ontology/
  - make &> log.txt
  - tail -n 100 log.txt
  # now check for duplicated labels, synonyms that are used for different classes
  - cd $CI_HOME
  - java -jar $OBO_CHECK_JAR $HP_OBO


