## REMEMBER TO SET UP YOUR GITHUB REPO FOR TRAVIS
## Go to: https://travis-ci.org/obophenotype for details
sudo: required

dist: trusty

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull
  
# OLD PIPELINE
# store the home dir for later use
env:
  global:
    - CI_HOME=`pwd`/$REPO
    - HP_EDIT=src/ontology/hp-edit.owl
    - HP_OBO=src/ontology/hp.obo
    - OBO_CHECK_JAR=hpo-obo-qc/target/hpo-obo-qc-0.0.1-SNAPSHOT-jar-with-dependencies.jar
    - OWL_CHECK_JAR=hpo-owl-qc/target/hpo-owl-qc-0.0.1-SNAPSHOT-jar-with-dependencies.jar
    - JAVA_OPTS=-Xmx4g
    
jdk:
  - oraclejdk8

install:
  # owl-qc maven install
  - git clone https://github.com/Phenomics/hpo-owl-qc.git
  - cd hpo-owl-qc
  - mvn clean install
  # obo-qc maven install
  - cd $CI_HOME
  - git clone https://github.com/Phenomics/hpo-obo-qc.git
  - cd hpo-obo-qc
  - mvn clean install

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
    - test-travis

### Add your own lists here
### See https://github.com/INCATools/ontology-development-kit/issues/35
# who gets notified if build-status changes
notifications:
  email:
    recipients:
      - dr.sebastian.koehler@gmail.com
      - peter.robinson@jax.org
      - Leigh.Carmody@jax.org
      - vasilevs@ohsu.edu
      - nicolas.matentzoglu@gmail.com
    on_success: change
    on_failure: always

# perform quality checks
script: 
  - set -e
  - cd $CI_HOME
  # encoding test on hp-edit
  - iconv -f UTF-8 -t ISO-8859-15 $HP_EDIT > converted.txt || (echo "found special characters in ontology. remove those!"; exit 1)
  # java-based owl checks on hp-edit
  - java -jar $OWL_CHECK_JAR $HP_EDIT
  # The ODK QC and build: 
  - cd src/ontology && sh run.sh make test #&> log.txt
  #- tail -n 100 log.txt
  # now check hp.obo for duplicated labels, synonyms that are used for different classes
  - cd $CI_HOME
  - java -jar $OBO_CHECK_JAR $HP_OBO
