site_name: Human Phenotype Ontology (Documentation)
theme:
  name: material
  features:
    - content.tabs.link
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
plugins:
  - search
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - md_in_html
  - tables
site_url: https://obophenotype.github.io/human-phenotype-ontology/
repo_url: https://github.com/obophenotype/human-phenotype-ontology/

nav:
  - Home: index.md
  - Phenopackets: phenopackets.md
  - Annotations:
      - Intro: annotations/introduction.md
      - phenotype.hpoa: annotations/phenotype_hpoa.md
      - genes_to_phenotype.txt: annotations/genes_to_phenotype.md
      - phenotype_to_genes.txt: annotations/phenotype_to_genes.md
      - genes_to_disease.txt: annotations/genes_to_disease.md
  
  - Developers:
      - Tools: developers/tools.md
      - Documentation: developers/documentation.md
  - Editors guides:
      - Protege: editors/protege.md
      - Standard ODK workflows:
          - Overview: odk-workflows/index.md
          - Editors Workflow: odk-workflows/EditorsWorkflow.md
          - Release Workflow: odk-workflows/ReleaseWorkflow.md
          - Manage your ODK Repository: odk-workflows/RepoManagement.md
          - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
          - Imports management: odk-workflows/UpdateImports.md
          - Components management: odk-workflows/components.md
          - Managing the documentation: odk-workflows/ManageDocumentation.md
          - Managing your automated testing: odk-workflows/ManageAutomatedTest.md
          - Continuous Integration: odk-workflows/ContinuousIntegration.md
          - Your ODK Repository Overview: odk-workflows/RepositoryFileStructure.md 
      - Design Patterns:
          - Design Patterns Overview: templates/dosdp.md
  - Community: 
      - Introduction: community/index.md
      - Contributing: community/contributing.md
      - Cite the HPO: community/cite.md
      - HPO Internationalization Effort: https://obophenotype.github.io/hpo-translations/
     
