site_name: Human Phenotype Ontology (Documentation)
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
plugins:
  - search
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - md_in_html
  - tables
site_url: https://obophenotype.github.io/human-phenotype-ontology/
repo_url: https://github.com/obophenotype/human-phenotype-ontology/

extra_css:
  - css/custom.css

nav:
  - Home: index.md
  - Documentation:
    - Overview: documentation/overview.md
    - Clinical:
      - Clinician's guide: documentation/clinicians.md
      - HPO term selection: documentation/HPO_term_selection.md
    - FAQs: documentation/FAQs.md
  - Phenopackets: phenopackets.md
  - Annotations:
      - Intro: annotations/introduction.md
      - phenotype.hpoa: annotations/phenotype_hpoa.md
      - genes_to_phenotype.txt: annotations/genes_to_phenotype.md
      - phenotype_to_genes.txt: annotations/phenotype_to_genes.md
      - genes_to_disease.txt: annotations/genes_to_disease.md
  - Developers:
      - Tools: developers/tools.md
      - Mappings: developers/mappings.md
      - Documentation: developers/documentation.md
      - Running an HPO release: developers/release.md
      - Editors guides:
          - Protege: editors/protege.md
          - Standard ODK workflows:
              - Overview: odk-workflows/index.md
              - Editors Workflow: odk-workflows/EditorsWorkflow.md
              - Release Workflow: odk-workflows/ReleaseWorkflow.md
              - Manage your ODK Repository: odk-workflows/RepoManagement.md
              - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
              - Imports management: odk-workflows/UpdateImports.md
              - Components management: odk-workflows/components.md
              - Managing the documentation: odk-workflows/ManageDocumentation.md
              - Managing your automated testing: odk-workflows/ManageAutomatedTest.md
              - Continuous Integration: odk-workflows/ContinuousIntegration.md
              - Your ODK Repository Overview: odk-workflows/RepositoryFileStructure.md
          - Design Patterns:
              - Design Patterns Overview: templates/dosdp.md
  - Community:
      - Introduction: community/index.md
      - Contributing: community/contributing.md
      - Workshops: community/workshops.md
      - Cite the HPO: community/cite.md
      - HPO Internationalization Effort: https://obophenotype.github.io/hpo-translations/
  - Workshops:
      - Introduction: workshops/index.md
      - What is a good HPO term?: workshops/good_term.md
      - Rules For Good HPO Structure: workshops/good_structure.md
      - Disease annotations: workshops/annotations.md
      - Workshop procedure: workshops/practical.md

