site_name: Human Phenotype Ontology
theme:
  name: material
  features:
    - content.tabs.link
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

site_url: https://obophenotype.github.io/human-phenotype-ontology/
repo_url: https://github.com/obophenotype/human-phenotype-ontology/

nav:
  - Getting started: index.md
  - Cite: cite.md
  - How-to guides:
      - Standard ODK workflows:
          - Overview: odk-workflows/index.md
          - Editors Workflow: odk-workflows/EditorsWorkflow.md
          - Release Workflow: odk-workflows/ReleaseWorkflow.md
          - Manage your ODK Repository: odk-workflows/RepoManagement.md
          - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
          - Imports management: odk-workflows/UpdateImports.md
          - Components management: odk-workflows/components.md
          - Managing the documentation: odk-workflows/ManageDocumentation.md
          - Managing your automated testing: odk-workflows/ManageAutomatedTest.md
          - Continuous Integration: odk-workflows/ContinuousIntegration.md
          - Your ODK Repository Overview: odk-workflows/RepositoryFileStructure.md 
      - Contributing: contributing.md
  - Reference:
    - Design Patterns:
      - Design Patterns Overview: dosdp.md

